version: '2'
services:
  ### PHP-FPM Container
  php-fpm:
    build: ./build/php-fpm
    volumes_from:
      - application
    expose:
      - "9000"
    links:
      - mysql
      - redis
  
  ### NGINX Container
  nginx:
    build: ./build/nginx
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm

  ### MySQL Container
  mysql:
    build: ./build/mysql
    volumes:
      - /var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}

  ### Redis Container
  redis:
    image: redis
    expose:
        - "6379"

  ### Application Code Container
  application:
    build: ./build/application
    volumes:
      - ./src:/var/www

  ### Workspace Utilities Container
  workspace:
    build: ./build/workspace
    volumes_from:
      - application
    links:
      - mysql
      - redis
    tty: true